### ISSUE TITLE
Releases with everything I need to include procfile in other meta buildpacks?

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/procfile#3]
I was looking to add procfile to the ruby buildpack.toml but it does not publish releases https://github.com/paketo-community/ruby/issues/56

I'm sorry that I'm confused -- I still don't think I get my head around what repos are components and what are meta buildpacks, and different repos have very different looking buildpack.toml files.

In the ruby toml https://github.com/paketo-community/ruby/blob/master/buildpack.toml each dependency looks like:

```toml
  [[metadata.dependencies]]
    id = "paketo-community/mri"
    sha256 = "0dbaf9ee3ba9897f5b9ebedbe54a0bb6f8b8aa14320d131070ae10ba460a1810"
    source = "https://github.com/paketo-community/mri/archive/v0.0.121.tar.gz"
    source_sha256 = "331359db395f73cd4d3302601c1bf1ee9f0c24d8e3edee949e5258e5dbcd5c25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-community/mri/releases/download/v0.0.121/mri-0.0.121.tgz"
    version = "0.0.121"
```

But https://github.com/paketo-buildpacks/java/blob/c55437c0ff489dc58789a4f9191a3ef638b0325c/buildpack.toml uses procfile buildpack but the file doesn't include the `[[metadata.dependencies]]` I need. So confusing.

But the procfile project does not cut releases of a `procfile-1.3.6.tgz`. Could this project's CI please spit out releases + sample TOML that I'd use to add to ruby's buildpack.toml?
